export interface Guide { slug: string; title: string; description: string; sections: { heading: string; paragraphs: string[] }[]; practice: string; practiceLabel: string; }
export const guides: Guide[] = [
 {
  slug: "wpm-vs-kph", title: "WPM vs KPH: How to Read Your Typing Score", description: "Worked examples of WPM, numeric KPH, corrections and accuracy using WPMTest’s actual scoring rules.",
  sections: [
   { heading: "Match the measurement to the task", paragraphs: ["Prose typing measures how you reproduce sentences, spaces and punctuation. Numeric entry involves repeated digits, identifiers and decimal points. WPM is useful for prose; KPH expresses numeric entry as an hourly rate. Neither establishes that a complete customer or invoice record is correct.", "Compare the same device, passage type, duration and correction rules. Touchscreen scores are not interchangeable with physical-keyboard scores. For employment, the actual employer’s instructions take priority over general practice advice."] },
   { heading: "Worked WPM calculation", paragraphs: ["WPMTest’s main WPM is correct characters remaining in the passage divided by five, then divided by elapsed minutes. Spaces and punctuation count. This convention does not count dictionary words.", "For 250 correct characters in 60 seconds: (250 ÷ 5) ÷ 1 = 50 WPM. The same characters in two minutes give 25 WPM. If only 240 of 250 entered characters match, the main score after one minute is 48 WPM. Displayed values are rounded."] },
   { heading: "Corrections do not erase input history", paragraphs: ["Prose accuracy uses correct character inputs divided by all character inputs. Backspace is tracked separately. Correcting a wrong character repairs the final text but does not erase the original incorrect input from accuracy.", "Suppose 250 final characters are correct after five wrong inputs were deleted and retyped. If these are the only extra inputs, 250 of 255 character inputs were correct: 98.0% accuracy. Raw WPM uses all character inputs, so extra corrections can raise it. Raw speed is not a quality score."] },
   { heading: "KPH extrapolates a shorter sample", paragraphs: ["Numeric KPM is entered characters divided by elapsed minutes. KPH = KPM × 60. For 300 entered characters in three minutes, KPM is 100 and KPH is 6,000. This does not prove you can maintain that pace for an hour.", "WPMTest’s numeric tool counts separators between groups, including automatically inserted spaces. Backspace removes entries before scoring; numeric accuracy describes remaining text, not every corrected error. These rules differ from the prose trainer and may differ from employer software. Check formulas before comparing tools."] },
   { heading: "Choose the next exercise", paragraphs: ["For low prose accuracy, use the weak-key summary. For numeric errors, check decimal placement and leading zeroes before increasing pace. For large score swings, repeat comparable sessions instead of reporting only the fastest attempt.", "Record date, device, duration, WPM or KPH, accuracy and your most common error. Keep mobile and hardware-keyboard results separate. Your progress is saved locally; clearing browser data removes it unless you export a backup."] }
  ], practice: "/kph-typing-test/", practiceLabel: "Try the three-minute KPH test"
 },
 {
  slug: "data-entry-accuracy", title: "Data Entry Accuracy: Characters, Fields and Complete Records", description: "A worked 24-field example showing why one wrong digit matters despite a high character score.",
  sections: [
   { heading: "A nearly correct field can still be unusable", paragraphs: ["Entering KB-2048 instead of KB-2047 changes only one character, but may identify a different product. A character score makes the mistake look small. Exact-match field scoring treats the whole value as incorrect.", "Structured-record practice checks each submitted value against its source. Case, spaces, punctuation, decimals and leading zeroes must match. This evaluates copying the requested format; it does not establish whether another format would be accepted in a real business system."] },
   { heading: "Worked example: 23 of 24 fields", paragraphs: ["The general data-entry test uses four fictional records with six fields each. If 23 of 24 fields match, field accuracy is 23 ÷ 24 × 100 = 95.8%. If the error occurs in one record, only three of four records are completely correct: 75% complete-record accuracy.", "Field accuracy shows the proportion of usable values. Complete-record accuracy shows whole records needing no correction. Neither is prose keystroke accuracy. Specialized drills contain fewer fields; use the actual attempted-field count as the denominator."] },
   { heading: "Blank fields and speed", paragraphs: ["Pressing Enter or Next field with a blank input submits an incorrect field. A missing identifier or amount should not disappear from the result. After completion, the mistake list shows the expected and entered values.", "Fields per minute is fields attempted divided by elapsed minutes. Twenty-four fields in two minutes equals 12 fields per minute whether or not they were correct. Always read accuracy beside the rate. Faster entry with more unusable records is not improvement."] },
   { heading: "Turn mistakes into a practice plan", paragraphs: ["Code errors point toward Alphanumeric Entry. Amounts and dates point toward Currency & Dates. For names and addresses, slow down and compare spelling and spaces. The results page links to the field types you missed.", "Spend a few careful minutes on one error type, then repeat the same assessment under similar conditions. Repeating records introduces memorization, so treat the result as practice feedback rather than independent verification. The test does not measure spreadsheet knowledge, confidentiality or sustained work quality."] },
   { heading: "Describe the result accurately", paragraphs: ["This is a small, self-administered sample. It does not verify identity or confer accreditation. Printing the result creates a personal progress record, not an employer-approved qualification.", "For a job application, follow the employer’s required provider, duration and supervision rules. Use this test to discover what to practice before completing that assessment."] }
  ], practice: "/data-entry-typing-test/", practiceLabel: "Take the structured-record practice test"
 },
 {
  slug: "avoid-data-entry-errors", title: "Avoid Data Entry Errors: Digits, Decimals and Leading Zeroes", description: "Fictional examples and an interactive checking exercise for numeric and identifier mistakes.",
  sections: [
   { heading: "Read the structure before copying", paragraphs: ["An identifier is not necessarily a quantity. Code 00482 has five characters; replacing it with 482 loses information. An amount such as 147.28 has a decimal in a specific place. Identify whether the field is a name, code, date or amount before typing.", "Use fictional data for practice. Never paste real customer, financial or medical records into a public typing exercise or support report. The examples here are invented to teach checking habits."] },
   { heading: "Recognize three common patterns", paragraphs: ["Transposition: source A48291, entry A48921. The length is correct, but 2 and 9 have traded places. Compare identifiers in short chunks rather than assuming the same length means the same value.", "Decimal shift: source $147.28, entry $14.728. The digits look familiar while the value has changed. Check digits before and after the decimal, including the currency symbol when the exercise requires it.", "Lost leading zero: source 00482, entry 482. Exact-match scoring treats these as different. A spreadsheet numeric field may also remove leading zeroes; follow the real system’s field-type instructions. Typing practice does not test software configuration."] },
   { heading: "Dates require a stated convention", paragraphs: ["08/09/2026 is ambiguous without a format convention: August 9 or September 8. Copy the source exactly in this exercise. In real work, follow the documented format and clarify ambiguous instructions instead of guessing.", "A date can match its source and still be invalid or misinterpreted by another system. Exact matching evaluates copying accuracy, not all business rules. Remember that limit when describing a practice score."] },
   { heading: "Read, copy, check", paragraphs: ["Read one value, type it, then compare the entry with its source. For codes, check prefixes, digit groups and hyphens. For money, check whole-number and decimal digits. For names, check spelling and spaces.", "If one pattern keeps causing errors, slow down deliberately for that pattern. Practice Currency & Dates for formatting or Alphanumeric Entry for identifiers. Repeat the combined records test afterward and check whether incorrect fields decrease. Cleaner records matter more than a faster headline score."] }
  ], practice: "/data-entry-practice/currency-dates/", practiceLabel: "Practice currency and dates"
 },
 {
  slug: "prepare-employment-typing-test", title: "How to Prepare for an Employment Typing Test", description: "A practical checklist covering employer instructions, comparable practice, devices and certificate limits.",
  sections: [
   { heading: "Start with the actual instructions", paragraphs: ["There is no single requirement for every office or data-entry role. Find the specified duration, minimum speed, accuracy rule and input method. Check whether the assessment uses prose, numeric groups or structured records and whether corrections are allowed.", "Check whether a named provider, supervision or identity verification is required. A printable practice result does not replace a required proctored assessment. Ask the hiring contact about unclear instructions before practicing the wrong format."] },
   { heading: "Match your environment", paragraphs: ["Use a physical keyboard for a hardware-keyboard test and a numeric keypad for 10-key work. Touchscreen typing measures another input skill. Keep language, layout and device similar when comparing attempts.", "Use punctuation practice when capitals and symbols are included, and structured records for names, dates, amounts and identifiers. The three-minute KPH test supplies a sustained numeric sample, but its separator and correction rules may differ from employer software."] },
   { heading: "A suggested ten-minute routine", paragraphs: ["Spend two minutes warming up slowly, three minutes on a common error pattern, and five minutes on a comparable timed sample. This is a suggested routine, not a validated training prescription. Match the employer’s duration for your final practice check.", "Review the result before repeating. Low accuracy calls for slower focused practice. Repeated pauses may mean you need more familiarity with the passage format. Use the weak-key summary or structured-record mistake list to choose a drill. Stop if practice becomes uncomfortable."] },
   { heading: "Track repeatable performance", paragraphs: ["Record date, duration, device, format, score and accuracy. Compare several attempts under similar conditions. One unusually fast score can misrepresent what you reliably reproduce. Do not compare a short word burst with a longer punctuation passage.", "On assessment day, reread the instructions, confirm keyboard layout and complete any permitted practice step. Raise accessibility needs with the employer or provider in advance; this website cannot grant accommodations for their assessment."] },
   { heading: "Describe certificates honestly", paragraphs: ["A WPMTest certificate records a completed online test. It is self-administered, does not verify identity and is not accredited. Keep duration and accuracy beside the speed. Do not call it employer-approved or nationally recognized.", "Use practice to identify what to improve, then complete the assessment actually requested. Preparation is useful; collecting a certificate the employer will not accept is not a substitute."] }
  ], practice: "/typing-test-for-employment/", practiceLabel: "Practice employment prose typing"
 }
];
